---
#System Settings
php_modules: [ 'php5-curl', 'php5-gd', 'php5-mbstring', 'php5-xml', 'php5-xmlrpc', 'php5-soap', 'php5-intl', 'php5-zip' ]

#MySQL Settings
mysql_root_password: "password"
mysql_db: "wordpress"
mysql_user: "root"
mysql_password: "password"

#HTTP Settings
http_host: "johnnelson.tk"
http_conf: "johnnelson.tk.conf"
http_port: "80"
